
services:
  mysql:
    image: mysql:8.0
    container_name: sweetshop-mysql
    environment:
      MYSQL_DATABASE: sweetshop
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "3306:3306"
    command: ["--default-authentication-plugin=mysql_native_password"]
    volumes:
      - mysql-data:/var/lib/mysql
      - ./Incubyte_Project/docker/mysql-init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-hsweetshop-mysql", "-uroot", "-proot_password"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql-data: